### ISSUE TITLE
Login Page Design (Add Google, Facebook i.e Third Party OAuth Sign in options)

### ISSUE THREAD

**Issue by gmovernight** [COS301-SE-2024/Smart-Parking-System#38]
Redesign Figma Login Page with new Logo and new Theme colors added. Also add Third party OAuth options and Try to show users Profile on login, something like "Welcome Back Ruan!" with Ruan's Profile Photo on login.

**Comment by shizaamir1615** [comment]
[login.fig.zip](https://github.com/user-attachments/files/15749691/login.fig.zip)
